# Generated by Django 4.1.1 on 2022-09-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HomeInfo name')),
                ('about', models.TextField(verbose_name='HomeInfo about')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeInfo image')),
            ],
            options={
                'verbose_name': 'HomeInfo',
                'verbose_name_plural': 'HomeInfos',
            },
        ),
    ]
