# Generated by Django 4.1.1 on 2022-09-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homeproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Customer name')),
                ('about', models.TextField(verbose_name='Customer about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Customer image')),
            ],
            options={
                'verbose_name': 'HomeCustomer',
                'verbose_name_plural': 'HomeCustomers',
            },
        ),
    ]
