# Generated by Django 4.1.1 on 2022-09-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecustomer',
            name='about_en',
            field=models.TextField(null=True, verbose_name='Customer about'),
        ),
        migrations.AddField(
            model_name='homecustomer',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='Customer about'),
        ),
        migrations.AddField(
            model_name='homecustomer',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='Customer about'),
        ),
        migrations.AddField(
            model_name='homecustomer',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Customer name'),
        ),
        migrations.AddField(
            model_name='homecustomer',
            name='name_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='Customer name'),
        ),
        migrations.AddField(
            model_name='homecustomer',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Customer name'),
        ),
        migrations.AddField(
            model_name='homecustomeractive',
            name='about_en',
            field=models.TextField(null=True, verbose_name='Customer about'),
        ),
        migrations.AddField(
            model_name='homecustomeractive',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='Customer about'),
        ),
        migrations.AddField(
            model_name='homecustomeractive',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='Customer about'),
        ),
        migrations.AddField(
            model_name='homecustomeractive',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Customer name'),
        ),
        migrations.AddField(
            model_name='homecustomeractive',
            name='name_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='Customer name'),
        ),
        migrations.AddField(
            model_name='homecustomeractive',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Customer name'),
        ),
    ]
